namespace MorningApiApp.ExternalServices.NewsApiOrg.Enums
{
    public enum NewsSourceEnum
    {
        AbcNews,
        //AbcNewsAu, // "category": "general", "language": "en", "country": "au"
        //Aftenposten, // "category": "general", "language": "no", "country": "no"
        AlJazeeraEnglish,
        //AnsaIt, // "category": "general", "language": "it", "country": "it"
        //Argaam, // "category": "business", "language": "ar", "country": "sa"
        ArsTechnica,            // "category": "technology", "language": "en", "country": "us"
        //AryNews,                // "category": "general", "language": "ud", "country": "pk"
        //AssociatedPress,        // "category": "general", "language": "en", "country": "us"
        //AustralianFinancialReview,  // "category": "business", "language": "en", "country": "au"
        //Axios,                  // "category": "general", "language": "en", "country": "us"
        BBCNews,                // "category": "general", "language": "en", "country": "gb"
        BBCSport,               // "category": "sports", "language": "en", "country": "gb"
        Bild,                   // "category": "general", "language": "de", "country": "de"
        //BlastingNewsBR,         // "category": "general", "language": "pt", "country": "br"
        //BleacherReport,         // "category": "sports", "language": "en", "country": "us"
        Bloomberg,              // "category": "business", "language": "en", "country": "us"
        //BreitbartNews,          // "category": "general", "language": "en", "country": "us"
        BusinessInsider,        // "category": "business", "language": "en", "country": "us"
        //BusinessInsiderUK,      // "category": "business", "language": "en", "country": "gb"
        Buzzfeed,               // "category": "entertainment", "language": "en", "country": "us"
        //CBCNews,                // "category": "general", "language": "en", "country": "ca"
        CBSNews,                // "category": "general", "language": "en", "country": "us"
        CNN,                    // "category": "general", "language": "en", "country": "us"
        //CNNSpanish,             // "category": "general", "language": "es", "country": "us"
        CryptoCoinsNews,        // "category": "technology", "language": "en", "country": "us"
        //DerTagesspiegel,        // "category": "general", "language": "de", "country": "de"
        //DieZeit,                // "category": "business", "language": "de", "country": "de"
        //ElMundo,                // "category": "general", "language": "es", "country": "es"
        Engadget,               // "category": "technology", "language": "en", "country": "us"
        EntertainmentWeekly,    // "category": "entertainment", "language": "en", "country": "us"
        ESPN,                   // "category": "sports", "language": "en", "country": "us"
        //ESPNCricInfo,           // "category": "sports", "language": "en", "country": "us"
        //FinancialPost,          // "category": "business", "language": "en", "country": "ca"
        //Focus,                  // "category": "general", "language": "de", "country": "de"
        //FootballItalia,         // "category": "sports", "language": "en", "country": "it"
        //Fortune,                // "category": "business", "language": "en", "country": "us"
        //FourFourTwo,            // "category": "sports", "language": "en", "country": "gb"
        FoxNews,                // "category": "general", "language": "en", "country": "us"
        //FoxSports,              // "category": "sports", "language": "en", "country": "us"
        //Globo,                  // "category": "general", "language": "pt", "country": "br"
        GoogleNews,             // "category": "general", "language": "en", "country": "us"
        //GoogleNewsArgentina,    //"category": "general","language": "es","country": "ar"
        //GoogleNewsAustralia,    //"category": "general","language": "en","country": "au"
        //GoogleNewsBrasil,       //"category": "general","language": "pt","country": "br"
        //GoogleNewsCanada,       //"category": "general","language": "en","country": "ca"
        //GoogleNewsFrance,       //"category": "general","language": "fr","country": "fr"
        //GoogleNewsIndia,        //"category": "general","language": "en","country": "in"
        //GoogleNewsIsrael,       //"category": "general","language": "he","country": "is"
        //GoogleNewsItaly,        //"category": "general","language": "it","country": "it"
        //GoogleNewsRussia,       //"category": "general","language": "ru","country": "ru"
        //GoogleNewsSaudiArabia,  //"category": "general","language": "ar","country": "sa"
        GoogleNewsUK,           // "category": "general", "language": "en", "country": "gb"
        //GöteborgsPosten,        // "category": "general", "language": "se", "country": "se"
        //Gruenderszene,          // "category": "technology", "language": "de", "country": "de"
        HackerNews,             // "category": "technology", "language": "en", "country": "us"
        //Handelsblatt,           // "category": "business", "language": "de", "country": "de"
        IGN,                    // "category": "entertainment", "language": "en", "country": "us"
        //IlSole24Ore,            // "category": "business", "language": "it", "country": "it"
        Independent,            // "category": "general", "language": "en", "country": "gb"
        //Infobae,                // "category": "general", "language": "es", "country": "ar"
        //InfoMoney,              // "category": "business", "language": "pt", "country": "br"
        //LaGaceta,               // "category": "general", "language": "es", "country": "ar"
        //LaNacion,               // "category": "general", "language": "es", "country": "ar"
        //LaRepubblica,           // "category": "general", "language": "it", "country": "it"
        //LeMonde,                // "category": "general", "language": "fr", "country": "fr"
        //Lenta,                  // "category": "general", "language": "ru", "country": "ru"
        //Lequipe,                // "category": "sports", "language": "fr", "country": "fr"
        //LesEchos,               // "category": "business", "language": "fr", "country": "fr"
        //Liberation,             // "category": "general", "language": "fr", "country": "fr"
        //Marca,                  // "category": "sports", "language": "es", "country": "es"
        //Mashable,               // "category": "entertainment", "language": "en", "country": "us"
        MedicalNewsToday,       // "category": "health", "language": "en", "country": "us"
        //MSNBC,                  // "category": "general", "language": "en", "country": "us"
        //MTVNews,                // "category": "entertainment", "language": "en", "country": "us"
        //MTVNewsUK,              // "category": "entertainment", "language": "en", "country": "gb"
        NationalGeographic,     // "category": "science", "language": "en", "country": "us"
        NationalReview,         // "category": "general", "language": "en", "country": "us"
        NBCNews,                // "category": "general", "language": "en", "country": "us"
        //News24,                 // "category": "general", "language": "en", "country": "za"
        NewScientist,           // "category": "science", "language": "en", "country": "us"
        //NewsComAu,              // "category": "general", "language": "en", "country": "au"
        //Newsweek,               // "category": "general", "language": "en", "country": "us"
        NewYorkMagazine,        // "category": "general", "language": "en", "country": "us"
        NextBigFuture,          // "category": "science", "language": "en", "country": "us"
        //NFLNews,                // "category": "sports", "language": "en", "country": "us"
        //NHLNews,                // "category": "sports", "language": "en", "country": "us"
        //NRK,                    // "category": "general", "language": "no", "country": "no"
        Politico,               // "category": "general", "language": "en", "country": "us"
        Polygon,                // "category": "entertainment", "language": "en", "country": "us"
        RBC,                    // "category": "general", "language": "ru", "country": "ru"
        Recode,                 // "category": "technology", "language": "en", "country": "us"
        RedditRAll,             // "category": "general", "language": "en", "country": "us"
        Reuters,                // "category": "general", "language": "en", "country": "us"
        RT,                     // "category": "general", "language": "ru", "country": "ru"
        //RTE,                    // "category": "general", "language": "en", "country": "ie"
        //RTLNieuws,              // "category": "general", "language": "nl", "country": "nl"
        //SABQ,                   // "category": "general", "language": "ar", "country": "sa"
        //SpiegelOnline,          // "category": "general", "language": "de", "country": "de"
        //SvenskaDagbladet,       // "category": "general", "language": "se", "country": "se"
        //T3n,                    // "category": "technology", "language": "de", "country": "de"
        TalkSport,              // "category": "sports", "language": "en", "country": "gb"
        TechCrunch,             // "category": "technology", "language": "en", "country": "us"
        //TechCrunchCN,           // "category": "technology", "language": "zh", "country": "zh"
        TechRadar,              // "category": "technology", "language": "en", "country": "us"
        //TheAmericanConservative,// "category": "general", "language": "en", "country": "us"
        //TheGlobeAndMail,        // "category": "general", "language": "en", "country": "ca"
        //TheHill,                // "category": "general", "language": "en", "country": "us"
        //TheHindu,               // "category": "general", "language": "en", "country": "in"
        //TheHuffingtonPost,      // "category": "general", "language": "en", "country": "us"
        //TheIrishTimes,          // "category": "general", "language": "en", "country": "ie"
        //TheJerusalemPost,       // "category": "general", "language": "en", "country": "is"
        TheLadBible,            // "category": "entertainment", "language": "en", "country": "gb"
        TheNextWeb,             // "category": "technology", "language": "en", "country": "us"
        TheSportBible,          // "category": "sports", "language": "en", "country": "gb"
        //TheTimesOfIndia,        // "category": "general", "language": "en", "country": "in"
        TheVerge,               // "category": "technology", "language": "en", "country": "us"
        TheWallStreetJournal,   // "category": "business", "language": "en", "country": "us"
        TheWashingtonPost,      // "category": "general", "language": "en", "country": "us"
        //TheWashingtonTimes,     // "category": "general", "language": "en", "country": "us"
        Time,                   // "category": "general", "language": "en", "country": "us"
        USAToday,               // "category": "general", "language": "en", "country": "us"
        ViceNews,               // "category": "general", "language": "en", "country": "us"
        Wired,                  // "category": "technology", "language": "en", "country": "us"
        //WiredDe,                // "category": "technology", "language": "de", "country": "de"
        //WirtschaftsWoche,       // "category": "business", "language": "de", "country": "de"
        //XinhuaNet,              // "category": "general", "language": "zh", "country": "zh"
        //Ynet                    // "category": "general", "language": "he", "country": "is"
    }
}
